autocalibrate: true
broadcast: false
dev_names: [pc, pedal]
dev_type: {pc: DNG, pedal: WL}
imu_mode: {pedal: wireless}
streaming: true
streaming_delay: 0
streaming_duration: unlimited
streaming_interval: 0
streaming_slots:
  pedal: [getTaredOrientationAsQuaternion]
wired_port: {pc: /dev/ttyACM0}
wireless_dng: {pedal: pc}
wireless_id: {pedal: 7}
